<script setup>
import {inject, onMounted, ref, watch} from "vue";
import BasicCategoryPicker from "components/basics/BasicCategoryPicker.vue";
const camelToReadable = inject('camelToReadable');

//! ALL SEARCH PARAMETERS ARE GENERATED BY MODELS FOUND IN THIS PROVIDED OBJECT!
const models = inject('models');

const props = defineProps({
  allCategories: {
    type: Array,
    default: [],
  },
  searchCategories: {
    type: Array,
    default: [],
  },
  searchProperties: {
    type: Array,
    default: [],
  }
});

const EXCLUDED = ['readingLog'];
const expanded = ref(false);
const properties = ref([]);
const propertyOptions = ref([]);

watch(properties, (n, o) => {
  //! Need to decide how to add/remove items found in 'n' from props.selectedProperties.
});

function clearSearchProperties() {

}

function initCheckboxes() {
  let properties = Object.keys(new models.Book());
  for(let p of properties) {
    if(EXCLUDED.includes(p)) continue;
    propertyOptions.value.push({label: camelToReadable(p), value: p});
  }
}

onMounted(() => {
  initCheckboxes();
});
</script>

<template>
  <q-expansion-item
    v-model="expanded"
    icon="tune"
    label="Search Options"
    class="bg-primary"
    dark>
    <template #header>
      <span class="q-pr-md">
        <q-icon size="lg" name="tune"></q-icon>
      </span>
      <span class="text-h6">
        Search Options
      </span>
      <q-space></q-space>
    </template>
    <q-card>
      <q-card-section>
        <div class="row">
          <div class="col-12 col-md-6 q-pb-md">


            <span class="text-subtitle1">Advanced Search</span>
            {{searchProperties}}{{properties}}
            <q-option-group
              class="q-pb-sm"
              :options="propertyOptions"
              type="checkbox"
              v-model="properties"
              dense
            >
              <template #label="{label}">
                <span style="font-variant-caps: small-caps;">{{label}}</span>
              </template>
            </q-option-group>
            <q-btn flat dense @click="clearSearchProperties"><q-icon name="clear_all" size="md"/>Clear All</q-btn>

          </div>
          <div class="col-12 col-md-6">
            <BasicCategoryPicker :all-categories="allCategories" :selected-categories="searchCategories" :appendable="false"/>
          </div>
        </div>
      </q-card-section>
    </q-card>
  </q-expansion-item>
</template>

<style scoped>

</style>
